/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 农产品平台 - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'user.get_admin_user_list': ['GET', '/admin/user/list'],
  'user.put_admin_user_id': ['PUT', '/admin/user/{id}'],
  'user.delete_admin_user_id': ['DELETE', '/admin/user/{id}'],
  'newsCategories.post_admin_news_categories': ['POST', '/admin/news/categories'],
  'newsCategories.get_admin_news_categories_list': ['GET', '/admin/news/categories/list'],
  'newsCategories.put_admin_news_categories_id': ['PUT', '/admin/news/categories/{id}'],
  'newsCategories.delete_admin_news_categories_id': ['DELETE', '/admin/news/categories/{id}'],
  'news.post_admin_news': ['POST', '/admin/news'],
  'news.get_admin_news_list': ['GET', '/admin/news/list'],
  'news.get_admin_news_id': ['GET', '/admin/news/{id}'],
  'news.put_admin_news_id': ['PUT', '/admin/news/{id}'],
  'news.delete_admin_news_id': ['DELETE', '/admin/news/{id}'],
  'news.put_admin_news_status_id': ['PUT', '/admin/news/status/{id}'],
  'goods.get_public_good_list': ['GET', '/public/good/list'],
  'goods.get_public_good_id': ['GET', '/public/good/{id}'],
  'goods.delete_public_good_id': ['DELETE', '/public/good/{id}'],
  'goods.post_public_good': ['POST', '/public/good'],
  'goods.get_public_good_id_comment': ['GET', '/public/good/{id}/comment'],
  'goods.post_public_good_id_comment': ['POST', '/public/good/{id}/comment'],
  'goods.get_public_good_comment_id': ['GET', '/public/good/comment/{id}'],
  'goods.delete_public_good_comment_id': ['DELETE', '/public/good/comment/{id}'],
  'user.put_public_user': ['PUT', '/public/user'],
  'user.get_public_user': ['GET', '/public/user'],
  'user.post_public_user_avatar': ['POST', '/public/user/avatar'],
  'user.get_public_user_id': ['GET', '/public/user/{id}'],
  'general.get_files_types_name': ['GET', '/files/{types}/{name}'],
  'general.post_public_files_types': ['POST', '/public/files/{types}'],
  'general.delete_public_files_types_name': ['DELETE', '/public/files/{types}/{name}'],
  'general.post_auth_login_code': ['POST', '/auth/login/code'],
  'general.post_auth_login_pwd': ['POST', '/auth/login/pwd'],
  'general.post_auth_register': ['POST', '/auth/register'],
  'general.post_auth_code': ['POST', '/auth/code'],
  'general.put_auth_password': ['PUT', '/auth/password']
};
