/* tslint:disable */
/* eslint-disable */
/**
 * 农产品平台 - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface Login {
  code: number;
  msg: string;
  data: {
    id: number;
    token: string;
    role: string;
  };
}
declare global {
  interface Apis {
    user: {
      /**
       * ---
       *
       * [GET] 获取用户列表
       *
       * **path:** /admin/user/list
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     total: number
       *     // [items] start
       *     // [items] end
       *     list: Array<{
       *       id: number
       *       phone: string
       *       nickname: string
       *       avatar_path: string
       *       role: string
       *       status: string
       *       created_at: string
       *     }>
       *   }
       * }
       * ```
       */
      get_admin_user_list<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              id: number;
              phone: string;
              nickname: string;
              avatar_path: string;
              role: string;
              status: string;
              created_at: string;
            }>;
          };
        }>
      >(
        config?: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              id: number;
              phone: string;
              nickname: string;
              avatar_path: string;
              role: string;
              status: string;
              created_at: string;
            }>;
          };
        },
        'user.get_admin_user_list',
        Config
      >;
      /**
       * ---
       *
       * [PUT] 修改用户信息
       *
       * **path:** /admin/user/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   nickname: string
       *   role: number
       *   status: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      put_admin_user_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          pathParams: {
            id: string;
          };
          data: {
            nickname: string;
            role: number;
            status: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'user.put_admin_user_id',
        Config
      >;
      /**
       * ---
       *
       * [DELETE] 删除用户
       *
       * **path:** /admin/user/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      delete_admin_user_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'user.delete_admin_user_id',
        Config
      >;
      /**
       * ---
       *
       * [PUT] 修改用户信息
       *
       * **path:** /public/user
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   nickname: string
       *   // 无法修改为管理员以上权限
       *   role: string
       *   avatar: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      put_public_user<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          data: {
            nickname: string;
            /**
             * 无法修改为管理员以上权限
             */
            role: string;
            avatar: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'user.put_public_user',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取当前用户信息
       *
       * **path:** /public/user
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     id: number
       *     phone: string
       *     nickname: string
       *     avatar_path: string
       *     role: string
       *     status: string
       *     created_at: string
       *   }
       * }
       * ```
       */
      get_public_user<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            id: number;
            phone: string;
            nickname: string;
            avatar_path: string;
            role: string;
            status: string;
            created_at: string;
          };
        }>
      >(
        config?: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            id: number;
            phone: string;
            nickname: string;
            avatar_path: string;
            role: string;
            status: string;
            created_at: string;
          };
        },
        'user.get_public_user',
        Config
      >;
      /**
       * ---
       *
       * [POST] 上传头像
       *
       * **path:** /public/user/avatar
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   avatar: Blob
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: object
       *   avatar: string
       * }
       * ```
       */
      post_public_user_avatar<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: object;
          avatar: string;
        }> & {
          data: {
            avatar: Blob;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: object;
          avatar: string;
        },
        'user.post_public_user_avatar',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取用户信息
       *
       * **path:** /public/user/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     id: number
       *     phone: string
       *     nickname: string
       *     avatar_path: string
       *     role: string
       *     status: string
       *     created_at: string
       *   }
       * }
       * ```
       */
      get_public_user_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            id: number;
            phone: string;
            nickname: string;
            avatar_path: string;
            role: string;
            status: string;
            created_at: string;
          };
        }> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            id: number;
            phone: string;
            nickname: string;
            avatar_path: string;
            role: string;
            status: string;
            created_at: string;
          };
        },
        'user.get_public_user_id',
        Config
      >;
    };
    newsCategories: {
      /**
       * ---
       *
       * [POST] 创建新闻分类
       *
       * **path:** /admin/news/categories
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   name: string
       *   description: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      post_admin_news_categories<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          data: {
            name: string;
            description: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'newsCategories.post_admin_news_categories',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取分类列表
       *
       * **path:** /admin/news/categories/list
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     total: number
       *     // [items] start
       *     // [items] end
       *     list: Array<{
       *       name: string
       *       description: string
       *       id: number
       *       sort_order: string
       *       created_at: string
       *     }>
       *   }
       * }
       * ```
       */
      get_admin_news_categories_list<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              name: string;
              description: string;
              id: number;
              sort_order: string;
              created_at: string;
            }>;
          };
        }>
      >(
        config?: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              name: string;
              description: string;
              id: number;
              sort_order: string;
              created_at: string;
            }>;
          };
        },
        'newsCategories.get_admin_news_categories_list',
        Config
      >;
      /**
       * ---
       *
       * [PUT] 修改新闻分类
       *
       * **path:** /admin/news/categories/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 名称
       *   name: string
       *   description: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      put_admin_news_categories_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          pathParams: {
            id: string;
          };
          data: {
            /**
             * 名称
             */
            name: string;
            description: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'newsCategories.put_admin_news_categories_id',
        Config
      >;
      /**
       * ---
       *
       * [DELETE] 删除新闻分类
       *
       * **path:** /admin/news/categories/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      delete_admin_news_categories_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'newsCategories.delete_admin_news_categories_id',
        Config
      >;
    };
    news: {
      /**
       * ---
       *
       * [POST] 提交新闻
       *
       * **path:** /admin/news
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   title: string
       *   category_id: number
       *   content: string
       *   // 只能填审核中和直接发布
       *   status: string
       *   cover_url: string
       *   // 只能填 新闻和政策
       *   types?: string
       *   // [items] start
       *   // [items] end
       *   files_url?: string[]
       *   abstract?: string
       *   // [items] start
       *   // [items] end
       *   keyword?: string[]
       *   source?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      post_admin_news<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          data: {
            title: string;
            category_id: number;
            content: string;
            /**
             * 只能填审核中和直接发布
             */
            status: string;
            cover_url: string;
            /**
             * 只能填 新闻和政策
             */
            types?: string;
            files_url?: string[];
            abstract?: string;
            keyword?: string[];
            source?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'news.post_admin_news',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取新闻列表
       *
       * **path:** /admin/news/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   title?: string
       *   author?: string
       *   status?: string
       *   page?: number
       *   count?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     total: number
       *     // [items] start
       *     // [items] end
       *     list: Array<{
       *       id?: number
       *       title?: string
       *       category_id?: number
       *       category?: string
       *       abstract?: string
       *       // [items] start
       *       // [items] end
       *       keyword?: string[]
       *       source?: string
       *       content?: string
       *       cover_url?: string
       *       // [items] start
       *       // [items] end
       *       files_url?: string[]
       *       status?: string
       *       author?: string
       *       type?: string
       *       created_at?: string
       *       updated_at?: string
       *     }>
       *   }
       * }
       * ```
       */
      get_admin_news_list<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              id?: number;
              title?: string;
              category_id?: number;
              category?: string;
              abstract?: string;
              keyword?: string[];
              source?: string;
              content?: string;
              cover_url?: string;
              files_url?: string[];
              status?: string;
              author?: string;
              type?: string;
              created_at?: string;
              updated_at?: string;
            }>;
          };
        }> & {
          params: {
            title?: string;
            author?: string;
            status?: string;
            page?: number;
            count?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              id?: number;
              title?: string;
              category_id?: number;
              category?: string;
              abstract?: string;
              keyword?: string[];
              source?: string;
              content?: string;
              cover_url?: string;
              files_url?: string[];
              status?: string;
              author?: string;
              type?: string;
              created_at?: string;
              updated_at?: string;
            }>;
          };
        },
        'news.get_admin_news_list',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取新闻详情
       *
       * **path:** /admin/news/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     id: number
       *     title: string
       *     category_id: number
       *     abstract: string
       *     // [items] start
       *     // [items] end
       *     keyword: string[]
       *     source: string
       *     content: string
       *     cover_url: string
       *     // [items] start
       *     // [items] end
       *     files_url: string[]
       *     status: string
       *     author: string
       *     created_at: string
       *     updated_at: string
       *   }
       *   // [title] 大类别(新闻/政策)
       *   type: string
       * }
       * ```
       */
      get_admin_news_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            id: number;
            title: string;
            category_id: number;
            abstract: string;
            keyword: string[];
            source: string;
            content: string;
            cover_url: string;
            files_url: string[];
            status: string;
            author: string;
            created_at: string;
            updated_at: string;
          };
          /**
           * 大类别(新闻/政策)
           * ---
           */
          type: string;
        }> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            id: number;
            title: string;
            category_id: number;
            abstract: string;
            keyword: string[];
            source: string;
            content: string;
            cover_url: string;
            files_url: string[];
            status: string;
            author: string;
            created_at: string;
            updated_at: string;
          };
          /**
           * 大类别(新闻/政策)
           * ---
           */
          type: string;
        },
        'news.get_admin_news_id',
        Config
      >;
      /**
       * ---
       *
       * [PUT] 修改新闻信息
       *
       * **path:** /admin/news/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   title?: string
       *   category_id?: number
       *   content?: string
       *   cover_url?: string
       *   // [items] start
       *   // [items] end
       *   files_url?: string[]
       *   abstract?: string
       *   types?: string
       *   // [items] start
       *   // [items] end
       *   keyword?: string[]
       *   source?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      put_admin_news_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          pathParams: {
            id: string;
          };
          data: {
            title?: string;
            category_id?: number;
            content?: string;
            cover_url?: string;
            files_url?: string[];
            abstract?: string;
            types?: string;
            keyword?: string[];
            source?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'news.put_admin_news_id',
        Config
      >;
      /**
       * ---
       *
       * [DELETE] 删除新闻
       *
       * **path:** /admin/news/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      delete_admin_news_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'news.delete_admin_news_id',
        Config
      >;
      /**
       * ---
       *
       * [PUT] 设置新闻状态
       *
       * **path:** /admin/news/status/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   status: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      put_admin_news_status_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          pathParams: {
            id: string;
          };
          data: {
            status: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'news.put_admin_news_status_id',
        Config
      >;
    };
    goods: {
      /**
       * ---
       *
       * [GET] 获取供需列表
       *
       * **path:** /public/good/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   title?: string
       *   page?: number
       *   count?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     total: number
       *     // [items] start
       *     // [items] end
       *     list: Array<{
       *       id: number
       *       userid: number
       *       created_at: string
       *       title: string
       *       content: string
       *       tag_name: string
       *       tag_weigh: string
       *       tag_price: string
       *       cover_url: string
       *       like: string
       *     }>
       *   }
       * }
       * ```
       */
      get_public_good_list<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              id: number;
              userid: number;
              created_at: string;
              title: string;
              content: string;
              tag_name: string;
              tag_weigh: string;
              tag_price: string;
              cover_url: string;
              like: string;
            }>;
          };
        }> & {
          params: {
            title?: string;
            page?: number;
            count?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              id: number;
              userid: number;
              created_at: string;
              title: string;
              content: string;
              tag_name: string;
              tag_weigh: string;
              tag_price: string;
              cover_url: string;
              like: string;
            }>;
          };
        },
        'goods.get_public_good_list',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取供需详情
       *
       * **path:** /public/good/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     id: number
       *     user_id: number
       *     title: string
       *     content: string
       *     cover_url: string
       *     // [items] start
       *     // [items] end
       *     files_url: string[]
       *     publisher_name: string
       *     created_at: string
       *     like: string
       *     tags: {
       *       name: string
       *       price: string
       *       weight: string
       *     }
       *   }
       * }
       * ```
       */
      get_public_good_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            id: number;
            user_id: number;
            title: string;
            content: string;
            cover_url: string;
            files_url: string[];
            publisher_name: string;
            created_at: string;
            like: string;
            tags: {
              name: string;
              price: string;
              weight: string;
            };
          };
        }> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            id: number;
            user_id: number;
            title: string;
            content: string;
            cover_url: string;
            files_url: string[];
            publisher_name: string;
            created_at: string;
            like: string;
            tags: {
              name: string;
              price: string;
              weight: string;
            };
          };
        },
        'goods.get_public_good_id',
        Config
      >;
      /**
       * ---
       *
       * [DELETE] 删除供需帖子
       *
       * **path:** /public/good/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      delete_public_good_id<
        Config extends Alova2MethodConfig<object> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'goods.delete_public_good_id', Config>;
      /**
       * ---
       *
       * [POST] 新建供需帖子
       *
       * **path:** /public/good
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // ID 编号
       *   title: string
       *   content: string
       *   cover: string
       *   // [items] start
       *   // [items] end
       *   files?: string[]
       *   tag_name?: string
       *   tag_weigh?: string
       *   tag_price?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      post_public_good<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          data: {
            /**
             * ID 编号
             */
            title: string;
            content: string;
            cover: string;
            files?: string[];
            tag_name?: string;
            tag_weigh?: string;
            tag_price?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'goods.post_public_good',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取评论列表
       *
       * **path:** /public/good/{id}/comment
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     total: number
       *     // [items] start
       *     // [items] end
       *     list: Array<{
       *       avatar: string
       *       id: string
       *       publisher_name: string
       *       comment: string
       *       role: string
       *       like: string
       *       user_id: number
       *       reply_id: number
       *       created_at: string
       *     }>
       *   }
       * }
       * ```
       */
      get_public_good_id_comment<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              avatar: string;
              id: string;
              publisher_name: string;
              comment: string;
              role: string;
              like: string;
              user_id: number;
              reply_id: number;
              created_at: string;
            }>;
          };
        }> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            total: number;
            list: Array<{
              avatar: string;
              id: string;
              publisher_name: string;
              comment: string;
              role: string;
              like: string;
              user_id: number;
              reply_id: number;
              created_at: string;
            }>;
          };
        },
        'goods.get_public_good_id_comment',
        Config
      >;
      /**
       * ---
       *
       * [POST] 新建评论
       *
       * **path:** /public/good/{id}/comment
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   comment: string
       *   reply_id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      post_public_good_id_comment<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          pathParams: {
            id: string;
          };
          data: {
            comment: string;
            reply_id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'goods.post_public_good_id_comment',
        Config
      >;
      /**
       * ---
       *
       * [GET] 获取评论详情
       *
       * **path:** /public/good/comment/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   comment?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     avatar: string
       *     id: string
       *     publisher_name: string
       *     comment: string
       *     role: string
       *     like: string
       *     user_id: number
       *     reply_id: number
       *     created_at: string
       *   }
       * }
       * ```
       */
      get_public_good_comment_id<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            avatar: string;
            id: string;
            publisher_name: string;
            comment: string;
            role: string;
            like: string;
            user_id: number;
            reply_id: number;
            created_at: string;
          };
        }> & {
          pathParams: {
            id: string;
          };
          params: {
            comment?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            avatar: string;
            id: string;
            publisher_name: string;
            comment: string;
            role: string;
            like: string;
            user_id: number;
            reply_id: number;
            created_at: string;
          };
        },
        'goods.get_public_good_comment_id',
        Config
      >;
      /**
       * ---
       *
       * [DELETE] 删除评论
       *
       * **path:** /public/good/comment/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: string
       * }
       * ```
       */
      delete_public_good_comment_id<
        Config extends Alova2MethodConfig<{
          code: string;
        }> & {
          pathParams: {
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: string;
        },
        'goods.delete_public_good_comment_id',
        Config
      >;
    };
    general: {
      /**
       * ---
       *
       * [GET] 获取图片信息
       *
       * **path:** /files/{types}/{name}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   types: string
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_files_types_name<
        Config extends Alova2MethodConfig<object> & {
          pathParams: {
            types: string;
            name: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.get_files_types_name', Config>;
      /**
       * ---
       *
       * [POST] 上传文件
       *
       * **path:** /public/files/{types}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   types: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   file: Blob
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     name: string
       *   }
       * }
       * ```
       */
      post_public_files_types<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            name: string;
          };
        }> & {
          pathParams: {
            types: string;
          };
          data: {
            file: Blob;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            name: string;
          };
        },
        'general.post_public_files_types',
        Config
      >;
      /**
       * ---
       *
       * [DELETE] 删除预览文件
       *
       * **path:** /public/files/{types}/{name}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   types: string
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      delete_public_files_types_name<
        Config extends Alova2MethodConfig<object> & {
          pathParams: {
            types: string;
            name: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.delete_public_files_types_name', Config>;
      /**
       * ---
       *
       * [POST] 验证码登录
       *
       * **path:** /auth/login/code
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   phone: string
       *   auth_code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     id: number
       *     token: string
       *     role: string
       *   }
       * }
       * ```
       */
      post_auth_login_code<
        Config extends Alova2MethodConfig<Login> & {
          data: {
            phone: string;
            auth_code: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Login, 'general.post_auth_login_code', Config>;
      /**
       * ---
       *
       * [POST] 密码登录
       *
       * **path:** /auth/login/pwd
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   phone: string
       *   password: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   data: {
       *     id: number
       *     token: string
       *     role: string
       *   }
       * }
       * ```
       */
      post_auth_login_pwd<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          data: {
            id: number;
            token: string;
            role: string;
          };
        }> & {
          data: {
            phone: string;
            password: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          data: {
            id: number;
            token: string;
            role: string;
          };
        },
        'general.post_auth_login_pwd',
        Config
      >;
      /**
       * ---
       *
       * [POST] 注册账号
       *
       * **path:** /auth/register
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   phone: string
       *   password: string
       *   auth_code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      post_auth_register<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          data: {
            phone: string;
            password: string;
            auth_code: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'general.post_auth_register',
        Config
      >;
      /**
       * ---
       *
       * [POST] 发送手机验证码
       *
       * **path:** /auth/code
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   phone: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_auth_code<
        Config extends Alova2MethodConfig<object> & {
          data: {
            phone: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_auth_code', Config>;
      /**
       * ---
       *
       * [PUT] 修改密码
       *
       * **path:** /auth/password
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   phone: string
       *   auth_code: string
       *   password: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       * }
       * ```
       */
      put_auth_password<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
        }> & {
          data: {
            phone: string;
            auth_code: string;
            password: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
        },
        'general.put_auth_password',
        Config
      >;
    };
  }

  var Apis: Apis;
}
